<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8radZh0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8radZh0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8radZh0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8radZh0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8radZh0\App_KernelDevDebugContainer([
    'container.build_hash' => '8radZh0',
    'container.build_id' => 'a36dd3ff',
    'container.build_time' => 1603993764,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8radZh0');
