<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTT9Dioj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTT9Dioj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTT9Dioj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTT9Dioj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTT9Dioj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TT9Dioj',
    'container.build_id' => 'ced05a4a',
    'container.build_time' => 1604687995,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTT9Dioj');
